# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: week3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='week3.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bweek3.proto\"9\n\x0crequest_lock\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04lock\x18\x02 \x01(\x08\x12\r\n\x05\x63lock\x18\x03 \x01(\x05\"<\n\x0clock_success\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x63lock\x18\x02 \x01(\x05\"N\n\x0frequest_service\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\x12\r\n\x05\x63lock\x18\x04 \x01(\x05\"8\n\x07success\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\r\n\x05money\x18\x06 \x01(\x05\x12\r\n\x05\x63lock\x18\x07 \x01(\x05\x32:\n\x0bRPCServicer\x12+\n\x0bMsgDelivery\x12\x10.request_service\x1a\x08.success\"\x00\x62\x06proto3'
)




_REQUEST_LOCK = _descriptor.Descriptor(
  name='request_lock',
  full_name='request_lock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='request_lock.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lock', full_name='request_lock.lock', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='request_lock.clock', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=72,
)


_LOCK_SUCCESS = _descriptor.Descriptor(
  name='lock_success',
  full_name='lock_success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='lock_success.user', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='lock_success.success', index=1,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='lock_success.clock', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=134,
)


_REQUEST_SERVICE = _descriptor.Descriptor(
  name='request_service',
  full_name='request_service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='request_service.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='request_service.request', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='request_service.money', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='request_service.clock', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=214,
)


_SUCCESS = _descriptor.Descriptor(
  name='success',
  full_name='success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='success.success', index=0,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='success.money', index=1,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='success.clock', index=2,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=272,
)

DESCRIPTOR.message_types_by_name['request_lock'] = _REQUEST_LOCK
DESCRIPTOR.message_types_by_name['lock_success'] = _LOCK_SUCCESS
DESCRIPTOR.message_types_by_name['request_service'] = _REQUEST_SERVICE
DESCRIPTOR.message_types_by_name['success'] = _SUCCESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request_lock = _reflection.GeneratedProtocolMessageType('request_lock', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST_LOCK,
  '__module__' : 'week3_pb2'
  # @@protoc_insertion_point(class_scope:request_lock)
  })
_sym_db.RegisterMessage(request_lock)

lock_success = _reflection.GeneratedProtocolMessageType('lock_success', (_message.Message,), {
  'DESCRIPTOR' : _LOCK_SUCCESS,
  '__module__' : 'week3_pb2'
  # @@protoc_insertion_point(class_scope:lock_success)
  })
_sym_db.RegisterMessage(lock_success)

request_service = _reflection.GeneratedProtocolMessageType('request_service', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST_SERVICE,
  '__module__' : 'week3_pb2'
  # @@protoc_insertion_point(class_scope:request_service)
  })
_sym_db.RegisterMessage(request_service)

success = _reflection.GeneratedProtocolMessageType('success', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESS,
  '__module__' : 'week3_pb2'
  # @@protoc_insertion_point(class_scope:success)
  })
_sym_db.RegisterMessage(success)



_RPCSERVICER = _descriptor.ServiceDescriptor(
  name='RPCServicer',
  full_name='RPCServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=274,
  serialized_end=332,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='RPCServicer.MsgDelivery',
    index=0,
    containing_service=None,
    input_type=_REQUEST_SERVICE,
    output_type=_SUCCESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPCSERVICER)

DESCRIPTOR.services_by_name['RPCServicer'] = _RPCSERVICER

# @@protoc_insertion_point(module_scope)
