# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import week3_pb2 as week3__pb2


class RPCServicerStub(object):
    """package RPCServicer;
    python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. week3.proto
    The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MsgDelivery = channel.unary_unary(
                '/RPCServicer/MsgDelivery',
                request_serializer=week3__pb2.request_service.SerializeToString,
                response_deserializer=week3__pb2.success.FromString,
                )


class RPCServicerServicer(object):
    """package RPCServicer;
    python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. week3.proto
    The greeting service definition.
    """

    def MsgDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPCServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MsgDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.MsgDelivery,
                    request_deserializer=week3__pb2.request_service.FromString,
                    response_serializer=week3__pb2.success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RPCServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPCServicer(object):
    """package RPCServicer;
    python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. week3.proto
    The greeting service definition.
    """

    @staticmethod
    def MsgDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RPCServicer/MsgDelivery',
            week3__pb2.request_service.SerializeToString,
            week3__pb2.success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
